services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Baschte\ContentAnimations\:
    resource: '../Classes/*'

  # Register all available content objects
  Baschte\ContentAnimations\ContentObject\FileContentContentObject:
    tags:
      - name: frontend.contentobject
        identifier: 'FILE'

  Baschte\ContentAnimations\DataProcessing\AnimationSettingsProcessor:
    tags:
      - { name: 'data.processor', identifier: 'animation-settings' }
